### ISSUE TITLE
Ctrl + Arrow already taken

### ISSUE THREAD

**Issue by Screenfeed** [nico3333fr/jquery-accessible-tabs-aria#1]
Hi Nico.

FYI, Ctrl + Arrow can't be done with OSX, they're already taken (unless the user customize them). Lets allow Alt + Arrow too?

**Comment by Screenfeed** [comment]
... and Alt + PageUp/PageDown of course, to keep it relevant.

**Comment by nico3333fr** [comment]
Hi,

in fact, I'm just respecting ARIA Design Pattern, but there are also problems on Chrome/Firefox : for example, Ctrl/PageUp will switch between tabs, unfortunately, nothing to do to avoid this. :-\

**Comment by Screenfeed** [comment]
Do ARIA Design Patterns forbid you to add more keyboard shortcuts than theirs?
I mean, if you keep Ctrl + WhateverKey, is it forbidden to also have Alt + WhateverKey for the same thing?
If they do, those pattern are obviously a failure (imho) :|
