### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by ffoodd** [nico3333fr/jquery-accessible-tabs-aria#10]
See the « [publishing npm package](https://docs.npmjs.com/getting-started/publishing-npm-packages) » documentation.

**Comment by GoOz** [comment]
:+1: NEED

**Comment by nico3333fr** [comment]
Je croule sous le taf :-\ 

Y a juste ce qui est indiqué dans la doc ci-dessus ou d'autres trucs à faire ? (fichiers à créer sur le repo, etc.)

Un peu d'aide please :)

**Comment by GoOz** [comment]
Il me semble qu'à minima il faut juste ajouter un package.json avec les infos de url, licence, etc dans le dépôt ce qui permet déjà d'installer le script à la main.
Le mieux serait en effet de le publish mais là j'ai jamais fait. Pas plus d'infos que n'en donne la page qu'à donner @ffoodd

**Comment by ffoodd** [comment]
Oui pour faire simple il faut ton fichier `package.json` (voici par exemple [celui d'a11y.css](https://github.com/ffoodd/a11y.css/blob/master/package.json)). 

Il faut installer NodeJS (probablement déjà le cas si tu joues avec Gulp ou autre joujou Node — et sinon [ça se passe là](https://nodejs.org/en/)). Tu peux tester avec la commande `node -v`. npm est installé avec Node donc tu l'auras forcément. Tu peux lancer `sudo npm install npm -g` pour mettre à jour ton npm.

Ensuite pour publier, le plus simple est de se créer un utilisateur npm _via_ [la page d'inscription](https://www.npmjs.com/signup). Puis sur ton poste, utilises la commande `npm login` pour te connecter à ton compte npm.

Pour finir tu navigues _via_ `cd` jusqu'au répertoire de ton projet. Il faut le `package.json` à la racine. Quand tu es dedans, tu peux lancer `npm publish`.

Pour vérifier que tout s'est bien passé, tu peux te rendre sur ton profil npm : ton nouveau projet devrait apparaitre en quelques secondes / minutes (cf [mon profil npm](https://www.npmjs.com/~ffoodd)).

Tout ce qu'on peut faire « à ta place » est de créer les `pakage.json`, je pense que pour la publication il vaut mieux que ça reste chez toi :)

PS: note les subtilités dans celui d'a11y.css, notamment les numéros de version et les dépendances : il faut bien penser à les maintenir en publiant une version. Mais tes modules sont assez softs donc ça ne devrait pas être trop dur :)

Ça aide ?

**Comment by ffoodd** [comment]
Hop, [un générateur de `package.json`](http://jspkg.com/generator) pour faire encore plus simple.

**Comment by dhoko** [comment]
How to publish packages to NPM -> https://gist.github.com/coolaj86/1318304

**Comment by nico3333fr** [comment]
Yop, merci !

J'ai créé le package.json, y a juste la dépendance à jquery que j'ai pas trop compris où mettre.

Je cherche à publier sur NPM…

**Comment by ffoodd** [comment]
Ça devrait être un truc dans ce genre-là : 

```
"dependencies": {
    "jquery": "latest"
  },
```

(`latest` peut aussi être un numéro de version, ou un indicateur de version avec des opérateurs, comme [le dit la doc](https://docs.npmjs.com/files/package.json#dependencies).

**Comment by nico3333fr** [comment]
Punaise, c'est TOP user-friendly comme truc.

Je crée mon compte en ligne, ok.

A la ligne de commande =>
`npm login` : pas de "!" dans le pass. Ok, j'update (c'eut été sympa de le dire en ligne).

`npm publish ./` faut être loggé. Ok.
Quand je tente un npm login pour faire le publish =>
`npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:nico3333fr`

Okay, on recommence en faisant ce que @dhoko a indiqué, ça passe. Je vais y arriver !

`npm publish =>  name can no longer contain capital letters.`

![enerve-colere-tire-tas](https://cloud.githubusercontent.com/assets/2578321/12235635/3f1086e2-b875-11e5-8334-d7a269ec55c8.gif)
RAAAAAAAAAAAAAAAAAAAAAAAAAAAAA !

Yo, on est en 2016, même Github permet de le faire en ligne avec un beau formulaire.

Bref => https://www.npmjs.com/~nico3333fr && https://www.npmjs.com/package/jquery-accessible-tabpanel-aria

Notre peuple vaincra. 

Vous pouvez tester que ça marche bien ?

**Comment by dhoko** [comment]
Peace&Love :+1: 

``` sh
[dev-02]:/tmp/test 
$ npm i jquery-accessible-tabpanel-aria
jquery-accessible-tabpanel-aria@1.0.2 ../node_modules/jquery-accessible-tabpanel-aria
└── jquery@2.2.0
```

```
[dev-02]:/tmp/node_modules 
$ ll jquery-accessible-tabpanel-aria/
total 48K
-rw-rw-r-- 1 aureliengarroux aureliengarroux  13K Jan 11 14:20 jquery-accessible-tabs.js
-rw-rw-r-- 1 aureliengarroux aureliengarroux  11K Jan 11 14:20 jquery-accessible-tabs_old_version.js
-rw-rw-r-- 1 aureliengarroux aureliengarroux 1.1K Jan 11 14:20 LICENSE
drwxrwxr-x 3 aureliengarroux aureliengarroux 4.0K Jan 11 15:14 node_modules/
-rw-rw-r-- 1 aureliengarroux aureliengarroux 1.7K Jan 11 15:14 package.json
-rw-rw-r-- 1 aureliengarroux aureliengarroux 3.6K Jan 11 14:20 README.md
-rw-rw-r-- 1 aureliengarroux aureliengarroux 2.4K Jan 11 14:20 sample.html
```

ça marche :)

Par contre la démo ne semble pas fonctionner.

**Comment by ffoodd** [comment]
Bien ouèj 😎

**Comment by nico3333fr** [comment]
Merci bien, encore une victoire de canard WC :+1: 

Et plus sérieusement, merci de m'avoir appris un nouveau truc :)

**Comment by nico3333fr** [comment]
Yop, c'est bon : j'ai pu updater. Merci bien, et see you soon :)
