### ISSUE TITLE
Issues using "first", "second", "third"

### ISSUE THREAD

**Issue by ricardozea** [nico3333fr/jquery-accessible-tabs-aria#11]
Hello,

I was trying to implement this tab system in a Glossary page, the tabs were the alphabet.

So in order to keep things simple, I changed:

```
id="label_id_first
id="label_id_second
id="label_id_third
…
```

to:

```
id="label_id_a
id="label_id_b
id="label_id_c
…
```

Now, when you go a URL with a fragment other than the first one, like `http://domain.com/glossary#b` it displays the content of the first tab.

See screenshots below.

Is there not a away to use other id labels rather than `first`, `second`, `third`?

![image](https://cloud.githubusercontent.com/assets/1656481/13956258/61ffcede-f01e-11e5-8b81-40ae6d209ac1.png)

![image](https://cloud.githubusercontent.com/assets/1656481/13956261/6641ecb6-f01e-11e5-9ba6-7f4129599d74.png)

**Comment by nico3333fr** [comment]
Hello,

Maybe you forgot to update the contents, here is the example:

```
<div class="js-tabs">
  <ul class="js-tablist" data-hx="h2">
   <li class="js-tablist__item">
    <a href="#id_a" id="label_id_a" class="js-tablist__link">A</a>
   </li>
   <li class="js-tablist__item">
    <a href="#id_b" id="label_id_b" class="js-tablist__link">B</a>
   </li>
etc.
  </ul>
 <div id="id_a" class="js-tabcontent">
   A
 </div>
 <div id="id_b" class="js-tabcontent">
   B
 </div>
 etc.
</div>
```

I've put in bold the changes :
a href="#**id_a**" id="**label_id_a**"
and 
div id="**id_a**" class="js-tabcontent"

Did you update also the tab panel id's in the source ?

**Comment by ricardozea** [comment]
Oh, ok, I see what the issue is.

I'm personally not a fan of using the underscore character `_`, I prefer hyphens `-` but seems the script is made to recognize underscores in the `id=""` attribute.

In other words, this doesn't work: `id="label-id-b"` - Notice the hyphen in `label-id-b`:

```
<a href="#id-b" id="label-id-b" class="js-tablist__link">B</a>
```

But this does: `id="label_id-b"` - Notice the underscore in `label_id-b`:

```
<a href="#id-b" id="label_id-b" class="js-tablist__link">B</a>
```

At least that's my tests showed.

Is this the case then?

**Comment by nico3333fr** [comment]
Yes, the pattern is `label_`, you are right (you may update it in the JS if needed, a quick search/replace will do the job :) ).

In a next version (coming really soon I hope ^^), there will be a parameter for this, so you will be able to change this convention to your needs. 

Is it ok for you ?

**Comment by ricardozea** [comment]
Yes, actually I just figured out that it was the underscore in the term `label_` that's mandatory.

I personally don't have any issues in using `label_x`, I would certainly prefer to use any naming convention I'd like. However, maybe just a documentation of this condition in the page and README would suffice rather than reworking the whole script and making it bigger for a small feature.

As you said, a mere search & replace would do, which is something you can also say in the README.

But that's your call :)

## 

On a side note, I almost couldn't figure out how to implement this script. It's actually very simple but the instructions in the site are a bit misleading, at least to me since I am not a developer by any means yet I'm capable of implementing scripts and functionalities in my builds without the need of a developer, at least before handoff.

The reason I say misleading is because in Step 3 of the How To Use It section you have a comment `// put the code of the plugin here`. I thought that after linking the main script in the `<head>`, I'd have to create a function in which I would put something to initiate the script, just like many other scripts behave. This script is different, it's actually MUCH simpler, but it's confusing.

All I needed to do was to call it from the `<head>` and that was it. Use the same HTML structure and done. All the styling is open to anything.

## 

Anyhow HUGE Thanks for your help on this and for making this script available for everyone.

**Comment by nico3333fr** [comment]
Okay, 

I guess I will have to enhance the doc. :)

Thanks for your remarks.
Nicolas
