### ISSUE TITLE
class="js-tablist__link" may cause bloating

### ISSUE THREAD

**Issue by ricardozea** [nico3333fr/jquery-accessible-tabs-aria#12]
Hello again Nicolas,

This is not an issue per se, but here's something for you to think about. This is more from an HTML and CSS standpoints rather than JS.

Having all `<li>`s have the class `class="js-tablist__link"` may bloat the HTML unnecessarily. I also say this because seems that having the class in the `<li>`s is required, which I think having a class in them should be optional.

This:

```
<ul class="js-tablist">
    <li><a href="#a" id="label_a" class="js-tablist__link">A</a></li>
    <li><a href="#b" id="label_b" class="js-tablist__link">B</a></li>
    <li><a href="#c" id="label_c" class="js-tablist__link">C</a></li>
    <li><a href="#d" id="label_d" class="js-tablist__link">D</a></li>
…
</ul>
```

Can be turned into this:

```
<ul class="js-tablist">
    <li><a href="#a" id="label_a">A</a></li>
    <li><a href="#b" id="label_b">B</a></li>
    <li><a href="#c" id="label_c">C</a></li>
    <li><a href="#d" id="label_d">D</a></li>
…
</ul>
```

And if we need to target the `<li>`s or links, we do:

```
.js-tablist > li { … }
.js-tablist > li > a { … }
```

Just a thought, I do not know what the JS implications of this would be :)

**Comment by nico3333fr** [comment]
Hello again,

Yes, or we could generate classes on the fly, also a possibility (which would avoid me redevelopping everything).

I keep the idea, and I will ask other users what they think of your idea.

Thanks a lot,
Nicolas

**Comment by ricardozea** [comment]
No problem, glad to help.
