### ISSUE TITLE
Not possible to move focus to tabs wit no links or form elements

### ISSUE THREAD

**Issue by sophieschuermans** [nico3333fr/jquery-accessible-tabs-aria#2]
Hello Nico,
I was just testing your example with my colleague who uses Jaws and we noticed that we couldn't read the content of the 1st, 2nd and 4th tab because it is not possible to move the focus there. The arrow keys change the focus between tabs and the only way to read the content of a tab is to first move the focus there by using the TAB key. This works for the 3rd tab because it has a form element, but not for the tabs that only contain text. 

I went back to the design pattern. It says 'The user reaches the tabbed panel component by pressing the tab key until the active tab title receives focus. '. 
I think the best solution is to allow the focus to be moved to the tabpanel div. 

Thanks for creating this example, 
Sophie

**Comment by nico3333fr** [comment]
Hello Sophie,

you are totally right, I'm going to fix this asap :)

Kind regards,
Nicolas

**Comment by sophieschuermans** [comment]
Merci Nicolas,
Je suis nouvelle sur github et c'était ma première issue :-) Mon ambition
est de pouvoir contribuer de manière plus active, mais je dois sérieusement
étudier le javascript parce que je suis encore loin d'être au point.
Si tu produis encore des widgets à l'avenir je les testerai avec plaisir.
On a vraiment besoin de pouvoir donner de bons exemples aux gens :-)

Bonne journée,

Sophie

2015-01-14 9:43 GMT+01:00 Nicolas Hoffmann notifications@github.com:

> Hello Sophie,
> 
> you are totally right, I'm going to fix this asap :)
> 
> Kind regards,
> Nicolas
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nico3333fr/jquery-accessible-tabs-aria/issues/2#issuecomment-69885212
> .

## 

## Sophie Schuermans

AnySurfer - Pour un internet plus accessible
Un projet de Blindenzorg Licht en Liefde vzw
24 bte 21 avenue des arts, 1000 Bruxelles
Tel: +32 (0)2-210 61 49
http://www.anysurfer.be/fr
Inscrivez-vous pour recevoir notre infolettre
http://anysurfer.us1.list-manage.com/subscribe?u=70958e7bb5&id=c7c6132db6

**Comment by nico3333fr** [comment]
De rien, merci à toi :)

J'ai modifié la démo (en ajoutant un tabindex="0" sur chaque contenu de tab), pourrais-tu réessayer ? http://www.nicolas-hoffmann.net/bordel/tabs/

Bonne soirée,
Nico

**Comment by nico3333fr** [comment]
Okay, c'est tout bon. Everything is ok. Thanks @sophieschuermans :)
