### ISSUE TITLE
Nested tab opened by default ?

### ISSUE THREAD

**Issue by nicoconi** [nico3333fr/jquery-accessible-tabs-aria#23]
Hello Nicolas,

I'm using your plugin with two levels of tabs, and I would like to know if there was a possibility to make a child tab opened by default (same that with data-selected=1) when clicking in the parent tab.

Tried to do it but I'm smashing my head on my keyboard right now :)

Thanks a lot ! Great plugin btw.

**Comment by nico3333fr** [comment]
Hello @nicoconi 

did you try the specific version for nested tabs? https://github.com/nico3333fr/jquery-accessible-tabs-aria/blob/master/jquery-accessible-nested-tabs.js

**Comment by nicoconi** [comment]
Tried it but the only problem for me is that it's not switching off the aria-selected="true" on the other .js-tablist__link... 
But at least, my first problem is now solved, thanks ;)

**Comment by nico3333fr** [comment]
So you have tabs in each tabs, and you want them to be opened by default. Isn't it the case with nested tabs script? (maybe if you have an URL, it will be easier to understand the problem for me)

**Comment by nicoconi** [comment]
No the all nested tab opened by default thing is solved ! 
I guess my problem now is with the stricter selectors, my list is a bit messy. It doesn't hide the tab-content anymore nor change the aria selected.
