### ISSUE TITLE
$('body') is not efficient

### ISSUE THREAD

**Issue by geoffreycrofte** [nico3333fr/jquery-accessible-tabs-aria#3]
Hi Nico,

Why did you use $('body') all along your document to bind elements?

For example:
`$(".tabs__link").on("click", function(e)){});`

shoul be more efficient than:
`$("body").on("click", ".tabs__link", function(e)){});`

It's not really an issue, more a curiosity.

Some reads:
http://stackoverflow.com/questions/12824549/should-all-jquery-events-be-bound-to-document
http://www.sitepoint.com/jquery-body-on-document-on/

Thank you for your work!

**Comment by ghost** [comment]
Instead of `$('body').on('click', '.tabs__link', function(e){});`, I would use `$(document).on('click', '.tabs__link', function(e){});`.

**Comment by nico3333fr** [comment]
@creativejuiz it is an issue, I didn't pay attention to optimize this, to be honest :)

However, the main difference is if you insert tabs after executing the script, the delegation .on will make it work anyway, am I right ?

@victorbritopro : what is the difference ?

**Comment by geoffreycrofte** [comment]
@nico3333fr : yes, your are right, but you could bind ("live") in that case the closest parent of tabs element.

About @victorbritopro 's proposition:  I think `document` is more global than `body`, and more "native". "`'body'`" selector will use the Sizzle.js engine selector. But have more global binds is not always recommended.

**Comment by ghost** [comment]
@creativejuiz The problem about the `live()` method is that it has been deprecated since jQuery 1.7 and removed since jQuery 1.9. The problem is the same with the `delegate()` method, which has been superseded by the `on()` method since jQuery 1.7.

**Comment by geoffreycrofte** [comment]
@victorbritopro Yeah, I know that, but the "live" and "bind" words were more efficients in my sentence :p

**Comment by nico3333fr** [comment]
Sorry guys, I had some issues to fix with Voice Over. Now we're going to optimize perf :)

**Comment by ffoodd** [comment]
Hi! Up on this issue: I had to bind the click on `.tabs__link` as suggested by @creativejuiz because of a strange behavior on iPad. Listening the click event on `body` didn't work at all, as if the click event didn't bubble.

I don't know which iPad/browser was used (user feedback) but simply listening to the click event on tabs solved it.

I hope it helps :)

**Comment by nico3333fr** [comment]
@ffoodd strange, I've tested with my iPad 2, the example site http://a11y.nicolas-hoffmann.net/tabs/ works well. (?)

**Comment by ffoodd** [comment]
As I said, I don't even know which iPad or browser was used. I confirm it works well on iPad Air (the only one I have at work) on Safari's last version.

**Comment by nico3333fr** [comment]
It is noted for the next refactoring, I hope for ASAP. :)
