### ISSUE TITLE
utilisation aria-selected

### ISSUE THREAD

**Issue by goetsu** [nico3333fr/jquery-accessible-tabs-aria#5]
Il manque aria-selected="true/false" sur les tabs qd ils sont actifs ou pas cf : http://www.w3.org/TR/wai-aria-practices/#tabpanel

**Comment by nico3333fr** [comment]
Yop, 

en fait, j'avais mis que le selected="true" (pas le false). ^^ (calqué sur le aria-hidden="true")

ooooops ^^

**Comment by nico3333fr** [comment]
C'est corrigé, merci encore :)
