### ISSUE TITLE
Global namespace pollution

### ISSUE THREAD

**Issue by dhoko** [nico3333fr/jquery-accessible-tabs-aria#7]
Hi,

You should use the keyword `var` for these variable declarations:
[L12](https://github.com/nico3333fr/jquery-accessible-tabs-aria/blob/master/jquery-accessible-tabs.js#L12)
[L16](https://github.com/nico3333fr/jquery-accessible-tabs-aria/blob/master/jquery-accessible-tabs.js#L16)

;)

**Comment by nico3333fr** [comment]
Oops, fixed :)
