### ISSUE TITLE
Caching jQuery main selector

### ISSUE THREAD

**Issue by dhoko** [nico3333fr/jquery-accessible-tabs-aria#8]
Hi, 

You should use the cache to list each tabs cf [L16](https://github.com/nico3333fr/jquery-accessible-tabs-aria/blob/master/jquery-accessible-tabs.js#L16).

You can use:

``` js

// before
$tab_list = $( ".js-tablist" );

// After
var $tab_list = $tabs.find(".js-tablist");
```

It searches the DOM only in the context of $tabs ;)

Ref:
- http://programer.tips/2014/09/best-jquery-practices.html#caching-jquery-objects

![Use selectors wisely](http://i.imgur.com/C9LBtwc.png)

**Comment by nico3333fr** [comment]
Good point, updated :) 

![bisou](https://cloud.githubusercontent.com/assets/2578321/9442542/c40cfa68-4a7c-11e5-9614-7f3f94021616.gif)
