### ISSUE TITLE
Invisible content focusable ?

### ISSUE THREAD

**Issue by cescarment** [nico3333fr/jquery-accessible-tabs-aria#9]
Hello,
In the example (http://a11y.nicolas-hoffmann.net/tabs/), you use an invisible title H2, with a tabindex in order to make this element focusable.
Is it correct for WCAG ? I don't think so, the focus isn't visible : 

> 2.4.7 Focus Visible: Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible. (Level AA)

**Comment by nico3333fr** [comment]
Hello,

I've checked with a [WCAG expert](https://twitter.com/goetsu), he told me that it is correct, as the invisible h2 is only focusable (reach-able) but not operable.

Hope that this answers your question. :)
